Update cloudbuild_dev.yaml

diff --git a/cloudbuild_dev.yaml b/cloudbuild_dev.yaml
--- a/cloudbuild_dev.yaml
+++ b/cloudbuild_dev.yaml
@@ -16,6 +16,20 @@ steps:
    '-c',
    'docker pull gcr.io/$PROJECT_ID/connectivity || exit 0'
   ]
+# Step 2.5
+- name: 'gcr.io/$PROJECT_ID/android:30'
+  id: &code_quality 'Run code quality checks'
+  waitFor:
+    - *assemble_debug
+  args:
+    - '-c'
+    - |
+      ./gradlew -PdisablePreDex checkCode 2> check-logs.txt || echo "fail" > build-status.txt
+      cat check-logs.txt
+      if [[ "${_PUSH_TO_MASTER}" ]]; then
+        ./gradlew -PdisablePreDex dependencyUpdates
+      fi
+  
 # Step 3
 - name: gcr.io/cloud-builders/docker
   args: [
